### ISSUE TITLE
Webview 

### ISSUE THREAD

**Issue by brijeshambitious** [NivedithaKabbur/DailyFeed#1]
If possible pl implementation webview in read more button and there should be a back button.

Collapse toolbar would be good addon. 

Search features (within api with q endpoint)

**Comment by brijeshambitious** [comment]
Please do this if you find some time

Published dates also be there in headlines.

**Comment by NivedithaKabbur** [comment]
I don't see this as an issue. I think redirecting to the browser is a better option than having a webview. However you can make the changes as per your requirements.
